version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: occurrence-annotation-db
    environment:
      POSTGRES_DB: annotation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: occurrence-annotation-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Override database connection for Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/annotation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
      # Disable Zookeeper for local Docker development
      SPRING_CLOUD_ZOOKEEPER_ENABLED: false
      SPRING_CLOUD_ZOOKEEPER_DISCOVERY_ENABLED: false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data: